### ISSUE TITLE
Examples missing?

### ISSUE THREAD

**Issue by torgeir** [humangeo/leaflet-dvf#79]
Looking through some of your stuff here, curious about the work on the `WeightedFlowLine`, I noticed the examples seem to have gone missing

e.g http://data.thehumangeo.com/leaflet-dvf/examples/html/markers.html (can't resolve host)

**Comment by sfairgrieve** [comment]
Thanks for pointing this out.  Looking into it now - looks like humangeo.github.io URLs are being redirected to data.thehumangeo.com which is not something I did.

**Comment by sfairgrieve** [comment]
Should be fixed now.  Thanks again for the heads up!

**Comment by torgeir** [comment]
No problem! Yeah, that seems to be the case. 

I'm still seeing the same thing, though, from https://github.com/humangeo/leaflet-dvf/wiki/2.-Examples
The link to http://humangeo.github.com/leaflet-dvf/examples/html/runmap.html resolves to http://data.thehumangeo.com/leaflet-dvf/examples/html/runmap.html which does not load

**Comment by sfairgrieve** [comment]
Weird, those examples are working for me now - they no longer redirect to data.thehumangeo.com.  Let me do some more investigating.  Maybe it's taking awhile for the fix to be propagated?  One of my coworkers added a CNAME file to the top level repo for humangeo.github.io that pointed to data.thehumangeo.com.  I removed this file, which seems to have fixed things here, but it's weird that the change hasn't made its way everywhere.

**Comment by torgeir** [comment]
I'm in Norway, maybe it's just taking a while :smile: Let me check back some time later!

**Comment by torgeir** [comment]
Alright, probably a propagation issue. After accessing http://humangeo.github.io directly, subsequent access to http://humangeo.github.com, like for the runmap link, now also resolves correctly
